on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: ./build.sh host
      - name: Get AppImage Properties
        id: appimage_props
        run: ./build.sh props out/OpenLens-*.AppImage >> "$GITHUB_OUTPUT"
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: OpenLens-${{ steps.appimage_props.outputs.VERS }}.${{ steps.appimage_props.outputs.ARCH }}.AppImage
          path: out/OpenLens-*.AppImage
